apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  repositories: |
    - url: https://github.com/mk10969/ouchi-k8s-cd
      passwordSecret:
        name: 973706611a27f171bc1c17d3e784999df7708b1a
        key: password
      usernameSecret:
        name: mk10969
        key: username
