apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - upstream/install.yaml
patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: argocd-dex-server
    patch: |-
      - op: replace
        path: /spec/template/spec/initContainers/0/image
        value: "mk10969/argocd"
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: argocd-repo-server
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: "mk10969/argocd"
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: argocd-server
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: "mk10969/argocd"
  - target:
      group: apps
      version: v1
      kind: StatefulSet
      name: argocd-application-controller
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: "mk10969/argocd"
images:
  - name: mk10969/argocd
    newTag: v2.1.2
