apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - upstream/common.yaml
  - upstream/crds.yaml
  - upstream/operator.yaml

  - upstream/cluster-test.yaml
  # - upstream/cluster.yaml

  - upstream/ceph-block-pool-test.yaml
  # - upstream/ceph-block-pool.yaml

images:
  - name: ceph/ceph
    newTag: :v15.2.9
