apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - upstream/common.yaml
  - upstream/crds.yaml
  - upstream/operator.yaml
  - upstream/cluster.yaml
  - upstream/ceph-block-pool.yaml

patchesJson6902:
  # healthCheck error: Liveness probe failed
  # bugだと思われる。指定したプロパティのみオーバライドしない。。はぁ。
  # - target:
  #     group: ceph.rook.io
  #     version: v1
  #     kind: CephCluster
  #     name: rook-ceph
  #   patch: |-
  #     - op: replace
  #       path: /spec/healthCheck/livenessProbe/mon/disabled
  #       value: true

  # - target:
  #     group: ceph.rook.io
  #     version: v1
  #     kind: CephCluster
  #     name: rook-ceph
  #   patch: |-
  #     - op: replace
  #       path: /spec/healthCheck/livenessProbe/mgr/disabled
  #       value: true

  # - target:
  #     group: ceph.rook.io
  #     version: v1
  #     kind: CephCluster
  #     name: rook-ceph
  #   patch: |-
  #     - op: replace
  #       path: /spec/healthCheck/livenessProbe/osd/disabled
  #       value: true

  # - target:
  #     group: ceph.rook.io
  #     version: v1
  #     kind: CephCluster
  #     name: rook-ceph
  #   patch: |-
  #     - op: replace
  #       path: /spec/dashboard/ssl
  #       value: false

  - target:
      group: ceph.rook.io
      version: v1
      kind: CephCluster
      name: rook-ceph
    patch: |-
      - op: replace
        path: /spec/resources
        value: {mgr: {limits: {cpu: "500m", memory: "512Mi"}, requests: {cpu: "500m", memory: "512Mi"}}, mon: {limits: {cpu: "500m", memory: "2Gi"}, requests: {cpu: "500m", memory: "1Gi"}}}

images:
  - name: ceph/ceph
    newTag: :v15.2.9
