apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - upstream/components.yaml
patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: metrics-server
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/command
        value: ["/metrics-server", "--kubelet-insecure-tls", "--kubelet-preferred-address-types=InternalIP"]
