datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: vmsingle
        type: prometheus
        url: http://vmagent-vmagent-single:8429
        access: proxy
        isDefault: true

  # - name: CloudWatch
  #   type: cloudwatch
  #   access: proxy
  #   uid: cloudwatch
  #   editable: false
  #   jsonData:
  #     authType: default
  #     defaultRegion: us-east-1
