apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: ..
spec:
  project: default
  source:
    repoURL: https://github.com/mk10969/ouchi-k8s-cd
    targetRevision: HEAD
    path: argocd-app/base
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
