apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx-controller
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: ..
    notifications.argoproj.io/subscribe.app-sync-failed.slack: argocd
    notifications.argoproj.io/subscribe.app-sync-status-unknown.slack: argocd
    notifications.argoproj.io/subscribe.app-health-degraded.slack: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mk10969/ouchi-k8s-cd
    targetRevision: HEAD
    path: ingress-controller/base
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
