apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tekton-pipeline
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: ..
    notifications.argoproj.io/subscribe.on-deployed.slack: argocd
    notifications.argoproj.io/subscribe.app-sync-failed.slack: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mk10969/ouchi-k8s-cd
    targetRevision: HEAD
    path: tekton-pipeline/base
  destination:
    server: https://kubernetes.default.svc
    namespace: tekton-pipelines
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
