apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patchesStrategicMerge:
  - argocd.yaml
  - argocd-app.yaml
  - argocd-notification.yaml
  - metallb.yaml
  - ingress-controller.yaml
  - tekton-pipeline.yaml
  - tekton-triggers.yaml
  - tekton-dashboard.yaml
