apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
data:
  trigger.sync-operation-change: |
    - when: app.status.operationState.phase in ['Succeeded'] and app.status.health.status == 'Healthy'
      send: [app-deployed]
      oncePer: app.status.sync.revision
    - when: app.status.operationState.phase in ['Degraded']
      send: [app-health-degraded]
    - when: app.status.operationState.phase in ['Unknown']
      send: [app-sync-status-unknown]
    - when: app.status.operationState.phase in ['Error', 'Failed']
      send: [app-sync-failed]
