apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - ../base
patchesStrategicMerge:
  - argocd-notifications-cm.yaml
  - slack-secret.yaml
  - slack-cm.yaml
