apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - upstream/01-namespace.yaml
  - upstream/02-metallb.yaml
images:
  - name: metallb/controller
    newTag: v0.9.5
  - name: metallb/speaker
    newTag: v0.9.5
