kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: git-source-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-git-source-storage
