apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - upstream/tekton-pipeline.yaml

# fix: SharedResourceWarning
patches:
  - target:
      kind: CustomResourceDefinition
    patch: |
      $patch: delete
      kind: CustomResourceDefinition
      metadata:
        name: clustertasks.tekton.dev

  - target:
      kind: CustomResourceDefinition
    patch: |
      $patch: delete
      kind: CustomResourceDefinition
      metadata:
        name: conditions.tekton.dev

  - target:
      kind: CustomResourceDefinition
    patch: |
      $patch: delete
      kind: CustomResourceDefinition
      metadata:
        name: pipelineresources.tekton.dev

  - target:
      kind: CustomResourceDefinition
    patch: |
      $patch: delete
      kind: CustomResourceDefinition
      metadata:
        name: pipelineruns.tekton.dev

  - target:
      kind: CustomResourceDefinition
    patch: |
      $patch: delete
      kind: CustomResourceDefinition
      metadata:
        name: pipelines.tekton.dev

  - target:
      kind: CustomResourceDefinition
    patch: |
      $patch: delete
      kind: CustomResourceDefinition
      metadata:
        name: runs.tekton.dev

  - target:
      kind: CustomResourceDefinition
    patch: |
      $patch: delete
      kind: CustomResourceDefinition
      metadata:
        name: taskruns.tekton.dev

  - target:
      kind: CustomResourceDefinition
    patch: |
      $patch: delete
      kind: CustomResourceDefinition
      metadata:
        name: tasks.tekton.dev
