apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - upstream/01-install.yaml
patchesStrategicMerge:
  - upstream/02-configmap.yaml
images:
  - name: argoprojlabs/argocd-notifications
    newTag: latest
