apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - upstream/install.yaml
patchesStrategicMerge:
  - configmap.yaml
  - secret.yaml
images:
  - name: argoprojlabs/argocd-notifications
    newTag: latest
