apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
stringData:
  notifiers.yaml: |
    slack:
      username: argocd-bot
      token: xoxb-1869303991349-1857620827559-rKwdnToRnMFhAElnisJQNHtc
type: Opaque
