apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: grafana
spec:
  # ingress:
  #   enabled: True
  service:
    type: LoadBalancer
  # deployment:
  #   envFrom:
  #     - configMapRef:
  #         name: https-proxy
  #     - secretRef:
  #         name: github-auth-20200423
  #   securityContext:
  #     runAsUser: 10000
  config:
    log:
      mode: "console"
      level: "warn"
    auth:
      disable_login_form: False
      disable_signout_menu: True
    auth.anonymous:
      enabled: True
    # security:
    #   admin_password: secret
    #   admin_user: admin
    # analytics:
    #   check_for_updates: true
    # grafana_net:
    #   url: https://grafana.monitoring-system.svc
    # users:
    #   viewers_can_edit: true
    #   auto_assign_org_role: Viewer
  dashboardLabelSelector:
    - matchExpressions:
        - key: app
          operator: In
          values:
            - grafana
  resources:
    # Optionally specify container resources
    limits:
      cpu: 2000m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
