apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: grafana
spec:
  service:
    type: LoadBalancer
  deployment:
    envFrom:
      - configMapRef:
          name: https-proxy
      - secretRef:
          name: github-auth-20200423
    securityContext:
      runAsUser: 10000
  config:
    log:
      mode: "console"
      level: "warn"
    auth:
      disable_signout_menu: true
    auth.anonymous:
      enabled: true
    security:
      admin_password: secret
      admin_user: admin
    analytics:
      check_for_updates: true
    grafana_net:
      url: https://grafana.monitoring-system.svc
    # users:
    #   viewers_can_edit: true
    #   auto_assign_org_role: Viewer
  dashboardLabelSelector:
    - matchExpressions:
        - key: app
          operator: In
          values:
            - grafana
