apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-operator
spec:
  template:
    spec:
      containers:
        - name: grafana-operator
          args:
            - --grafana-image-tag=7.5.3-ubuntu
            - --grafana-plugins-init-container-image=mk10969/grafana_plugins_init
            - --grafana-plugins-init-container-tag=0.0.3
            - --scan-all
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
