apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: single
  namespace: monitoring-system
spec:
  extraArgs:
    promscrape.maxScrapeSize: "33554432"
  serviceScrapeSelector: {}
  podScrapeSelector: {}
  probeSelector: {}
  nodeScrapeSelector: {}
  staticScrapeSelector: {}
  replicaCount: 1
  remoteWrite:
    - url: "http://vmsingle-single:8429/api/v1/write"
  resources:
    requests:
      cpu: 100m
      memory: 200Mi
