apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: vmagent
  namespace: monitoring
spec:
  extraArgs:
    promscrape.maxScrapeSize: "33554432"
  serviceScrapeSelector: {}
  podScrapeSelector: {}
  probeSelector: {}
  nodeScrapeSelector: {}
  staticScrapeSelector: {}
  replicaCount: 3
  remoteWrite:
    - url: "http://vminsert-vmcluster.monitoring.svc:8480/insert/0/prometheus/api/v1/write"
  resources:
    requests:
      cpu: 100m
      memory: 200Mi
  podDisruptionBudget:
    minAvailable: 2
