apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - upstream/crd.yaml
  - upstream/manager.yaml
  - upstream/rbac.yaml
  # vm single
  - vmsingle.yaml
  - vmagent-single.yaml
  # vm cluster
  # - vmagent.yaml
  # - vmalert.yaml
  # - vmalertmanager.yaml
  # - vmcluster.yaml
  # - rules/argocd-scrape.yaml
