apiVersion: operator.victoriametrics.com/v1beta1
kind: VMSingle
metadata:
  name: vmsingle
  namespace: monitoring
spec:
  retentionPeriod: "10d"
  extraArgs:
    dedup.minScrapeInterval: 30s # should be equal to VMAgent's scrapeInterval (default 30s)
  # storage:
  #   accessModes:
  #     - ReadWriteOnce
  #   resources:
  #     requests:
  #       storage: 10Gi
  #   storageClassName: rook-ceph-block
  resources:
    requests:
      cpu: 100m
      memory: 300Mi
