name: Release

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "Kustomize Build"
        uses: karancode/kustomize-github-action@master
        with:
          kustomize_version: "4.2.0"
          kustomize_build_dir: "./argocd/prd"
          kustomize_comment: false
          kustomize_output_file: "./argocd.yaml"
          enable_alpha_plugins: true
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}

      - name: Upload argocd.yaml file to release
        uses: svenstaro/upload-release-action@2.1.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./argocd.yaml
          asset_name: argocd.yaml
          tag: ${{ github.ref }}
          overwrite: true
